# Generated by Django 3.2 on 2021-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hymo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('fathers_name', models.EmailField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
